name: FlutterGalleryApp
description: Amazing Flutter Project
author: Divasik

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  cached_network_image: ^2.2.0+1
  connectivity: ^0.4.9
  gallery_saver: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  fonts:
    - family: AppIcons
      fonts:
        - asset: assets/fonts/AppIcons.ttf